---
# Default Docker build arguments
DEFAULT_PYTHON_VERSION: "3.7"
DEFAULT_CUDA_VERSION: "11.0"
DEFAULT_NIGHTLY_RAPIDS_VERSION: "21.06"
DEFAULT_STABLE_RAPIDS_VERSION: "0.19"
DEFAULT_NEXT_RAPIDS_VERSION: "21.08"

# Libraries included in RAPIDS core devel images
RAPIDS_LIBS:
  - name: rmm
    repo_url: https://github.com/rapidsai/rmm.git
  - name: cudf
    repo_url: https://github.com/rapidsai/cudf.git
    update_submodules: no
  - name: cusignal
    repo_url: https://github.com/rapidsai/cusignal.git
  - name: cuxfilter
    repo_url: https://github.com/rapidsai/cuxfilter
  - name: cuspatial
    repo_url: https://github.com/rapidsai/cuspatial.git
  - name: cuml
    repo_url: https://github.com/rapidsai/cuml.git
    update_submodules: no
  - name: cugraph
    repo_url: https://github.com/rapidsai/cugraph.git
  - name: xgboost
    update_submodules: no
    repo_url: https://github.com/rapidsai/xgboost.git
    branch: rapids-v0.18
  - name: dask-cuda
    repo_url: https://github.com/rapidsai/dask-cuda.git
