name: Publish release images to NGC

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}

    - name: Login to NGC
      uses: docker/login-action@v3
      with:
        registry: nvcr.io
        username: ${{ secrets.NGC_DOCKER_USER }}
        password: ${{ secrets.NGC_DOCKER_PASSWORD }}

    - name: Run With DockerHub Token
      run: |
        #!/usr/bin/env bash
        set -e
        
        for CUDA in 11.2 11.8 12.0; do
            for PY in 3.9 3.10; do
            for type in base notebooks; do
                source="rapidsai/$type:23.08-cuda$CUDA-py$PY"
                target="nvcr.io/nvidia/rapidsai/$type:23.08-cuda$CUDA-py$PY"
                echo "$source => $target"
                docker run -v ~/.docker/config.json:/config.json quay.io/skopeo/stable:latest copy --multi-arch all --dest-authfile=/config.json docker://$source docker://$target
                done
            done
        done
